# Generated by Django 5.2.11 on 2026-09-27 08:10
#
# 로컬 DB에 수동 DDL로 생성돼 있던 idx_cd_cat_quarter를 마이그레이션으로 이관.
# 기본 AddIndex는 기존 DB에서 "already exists"로 실패하므로
# DB 쪽은 IF NOT EXISTS로 멱등 처리하고, 상태(state)에만 AddIndex를 반영한다.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_alter_storeinfo_상가업소번호_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS idx_cd_cat_quarter '
                        'ON analysis_commercialdata ("통합카테고리", "기준_년분기_코드");',
                    reverse_sql='DROP INDEX IF EXISTS idx_cd_cat_quarter;',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='commercialdata',
                    index=models.Index(
                        fields=['통합카테고리', '기준_년분기_코드'],
                        name='idx_cd_cat_quarter',
                    ),
                ),
            ],
        ),
    ]
